# fly.toml app configuration file generated for yew-app on 2024-10-18T17:49:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yew-app'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
